-- MySQL Script generated by MySQL Workbench
-- 01/28/17 00:10:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`goods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `idgoods` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgoods`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`history` (
  `idhistory` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `users_idusers` INT NULL,
  `goods_idgoods` INT NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`idhistory`),
  INDEX `fk_history_users1_idx` (`users_idusers` ASC),
  INDEX `fk_history_goods1_idx` (`goods_idgoods` ASC),
  CONSTRAINT `fk_history_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_goods1`
    FOREIGN KEY (`goods_idgoods`)
    REFERENCES `mydb`.`goods` (`idgoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `idprojects` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idprojects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activities` (
  `idactivities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `projects_idprojects` INT NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`idactivities`),
  INDEX `fk_activities_projects_idx` (`projects_idprojects` ASC),
  CONSTRAINT `fk_activities_projects`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `mydb`.`projects` (`idprojects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`donations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`donations` (
  `iddonations` INT NOT NULL,
  `amount` DECIMAL(50) NOT NULL,
  `users_idusers` INT NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`iddonations`),
  INDEX `fk_donations_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_donations_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activities_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activities_has_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activities_has_users` (
  `activities_idactivities` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`activities_idactivities`, `users_idusers`),
  INDEX `fk_activities_has_users_users1_idx` (`users_idusers` ASC),
  INDEX `fk_activities_has_users_activities1_idx` (`activities_idactivities` ASC),
  CONSTRAINT `fk_activities_has_users_activities1`
    FOREIGN KEY (`activities_idactivities`)
    REFERENCES `mydb`.`activities` (`idactivities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activities_has_users_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
